# Generated by Django 5.2.3 on 2025-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='insee_code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
