# Generated by Django 5.2.3 on 2025-06-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_town_insee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
